 budgeting:
  outputs:
    dev:
      dataset: budgeting
      fixed_retries: 1
      keyfile: ../google_cloud_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: python-splitwise
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
