# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

env:
  SPLITWISE_CONSUMER_KEY: '${{ secrets.SPLITWISE_CONSUMER_KEY }}'
  SPLITWISE_CONSUMER_SECRET_KEY: '${{ secrets.SPLITWISE_CONSUMER_SECRET_KEY }}'
  SPLITWISE_API_KEY: '${{ secrets.SPLITWISE_API_KEY }}'
  ENCRYPT_KEY: '${{ secrets.ENCRYPT_KEY }}'
  GSHEET_SHEET_ID: '${{ secrets.GSHEET_SHEET_ID }}'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          cache: pip
      - run: pip install -r requirements.txt
      - name: update expenses py script
        run: |
          python src/update_expenses.py
      - name: upload expenses to splitiwse py script
        run: |
          python src/upload_expenses_to_splitwise.py
      - name: upload expenses to big query py script
        run: |
          python src/upload_expenses_to_bigquery.py
      - name: upload income to big query py script
        run: |
          python src/upload_income_to_bigquery.py
      - name: upload savings to big query py script
        run: |
          python src/upload_savings_to_bigquery.py
      - name: upload category dim to big query py script
        run: |
          python src/upload_category_dim_to_bigquery.py
      - name: upload exchange rate to big query py script
        run: |
          python src/upload_exchange_rate_to_bigquery.py
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          ENCRYPT_KEY: ${{ secrets. ENCRYPT_KEY }}
      - name: Install dependencies
        run: |
          pip install dbt-bigquery
      - name: Run DBT models
        run: |
          cd ./dbt/budgeting
          dbt run --profiles-dir .
      #- name: export index
      #  .... # use crosponding script or actions to help export.
